---
appveyor.yml:
  delete: true

.gitlab-ci.yml:
  delete: true

.rubocop_todo.yml:
  delete: true

.travis.yml:
  docker_sets:
    - set: docker/ubuntu-18.04
    - set: docker/ubuntu-16.04
    - set: docker/ubuntu-14.04
    - set: docker/debian-10
    - set: docker/debian-9
    - set: docker/debian-8
    - set: docker/centos-8
    - set: docker/centos-7

Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw

spec/spec.opts:
  delete: true

spec/spec_helper_local.rb:
  delete: true

.project:
  delete: true

locales/config.yaml:
  copyright_holder: 'Rehan Mahmood'
  comments_tag: 'TRANSLATOR'
  bugs_address: 'https://github.com/rehanone'
  default_locale: 'en'
  source_files:
    - './lib/**/*.rb'
